name: nomad-econ-yt

on:
  workflow_dispatch: {}
  schedule:
    - cron: '59 19 * * 6'  # Saturday 11:59 AM PT (19:59 UTC)
    - cron: '59 19 * * 0'  # Sunday   11:59 AM PT (19:59 UTC)

concurrency:
  group: nomad-econ-yt
  cancel-in-progress: false

jobs:
  build-run:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: System deps (ffmpeg & ImageMagick)
        run: |
          sudo apt-get update
          sudo apt-get install -y ffmpeg imagemagick

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Install Python deps
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt

      - name: Run agent
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
          PEXELS_API_KEY: ${{ secrets.PEXELS_API_KEY }}
          PIXABAY_API_KEY: ${{ secrets.PIXABAY_API_KEY }}
          YT_CLIENT_ID: ${{ secrets.YT_CLIENT_ID }}
          YT_CLIENT_SECRET: ${{ secrets.YT_CLIENT_SECRET }}
          YT_REFRESH_TOKEN: ${{ secrets.YT_REFRESH_TOKEN }}
          ELEVENLABS_API_KEY: ${{ secrets.ELEVENLABS_API_KEY }}
          ELEVENLABS_VOICE_ID: ${{ secrets.ELEVENLABS_VOICE_ID }}
        run: python agent.py

      - name: Upload artifacts (debug)
        if: always()
        uses: actions/upload-artifact@v4
        with:
          name: out
          path: |
            out/**
            out/img/**
            out/voice.mp3
            out/video.mp4
            out/thumb.png
          if-no-files-found: ignore
          retention-days: 7
